server:
  port: 8080
# mybatis-plus sql执行 debug日志追踪
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  # 配置Mybatis的mapper.xml扫描
  mybatis:
    mapper-locations: classpath:mapper/*.xml
  # Redis连接配置
  redis:
    host: 110.41.159.205
    port: 6379
    database: 0
    password: 123456
  # Thymeleaf使用
  thymeleaf:
    cache: false #开发时关闭缓存，不然看不到实时画面
  # 数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.41.159.205:3306/czhdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    #Hikari数据库连接池配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  mvc:
    pathmatch:
      #调整策略，解决2.6.4以上的高版本springboot与springfox不兼容的问题
      matching-strategy: ant_path_matcher


    # ----- (有问题，后面再看)下面的内容时Druid数据源的配置，springboot默认使用Hikari
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      #初始化连接池大小
#      initial-size: 5
#      #配置最小连接数
#      min-idle: 5
#      #配置最大连接数
#      max-active: 200
#      #配置连接等待超时时间
#      max-wait: 60000
#      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
#      #配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 300000
#      #测试连接
#      validation-query: SELECT 1 FROM DUAL
#      #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全
#      test-while-idle: true
#      #获取连接时执行检测，建议关闭，影响性能
#      test-on-borrow: false
#      #归还连接时执行检测，建议关闭，影响性能
#      test-on-return: false
#      #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
#      pool-prepared-statements: false
#      #开启poolPreparedStatements后生效
#      max-pool-prepared-statement-per-connection-size: 20
#      #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
#      filters: stat,wall,slf4j
#      #打开mergeSql功能；慢SQL记录
#      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
#      #配置DruidStatFilter
#      web-stat-filter:
#        enabled: true
#        url-pattern: "/*"
#        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
#      #配置DruidStatViewServlet
#      stat-view-servlet:
#        url-pattern: "/druid/*"
#        #登录名
#        login-username: root
#        #登录密码
#        login-password: root



